version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    healthcheck:
      test: "exit 0"
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
    # AMQP protocol port
    - "5672:5672"
    # HTTP management UI
    - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go

  gateway:
    container_name: mg_gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - RABBITMQ_USER=${RABBITMQ_USER}
    - RABBITMQ_PASS=${RABBITMQ_PASS}
    - PORT=${PORT}
    - SERVICE_RT=${SERVICE_RT_GATEWAY}
    env_file:
      - .env
    networks:
      - rabbitmq_go
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
     - "3000:3000"

  service:
   container_name: mg_service
   build:
     context: ./service_a
     dockerfile: Dockerfile
   environment:
    - RABBITMQ_HOST=${RABBITMQ_HOST}
    - RABBITMQ_USER=${RABBITMQ_USER}
    - RABBITMQ_PASS=${RABBITMQ_PASS}
    - PORT=${PORT}
    - SERVICE_RT=${SERVICE_RT_SERVICE}
   env_file:
     - .env
   networks:
     - rabbitmq_go
   depends_on:
     rabbitmq:
        condition: service_healthy

networks:
  rabbitmq_go:
    driver: bridge