version: "3.8"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    healthcheck:
      test: "exit 0"
    environment:
    - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
    - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
    # AMQP protocol port
    - "5672:5672"
    # HTTP management UI
    - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go
  api:
    container_name: mg_api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
    - MQ_HOST=${MQ_HOST}
    env_file:
      - .env
    networks:
      - rabbitmq_go
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
     - "3002:3002"
  web:
   container_name: mg_web
   build:
     context: ./web
     dockerfile: Dockerfile
   environment:
    - MQ_HOST=${MQ_HOST}
   env_file:
     - .env
   networks:
     - rabbitmq_go
   depends_on:
     rabbitmq:
        condition: service_healthy
   ports:
   - "3001:3001"

networks:
  rabbitmq_go:
    driver: bridge