version: "3.8"
services:
  api:
    container_name: mg_api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: 
     - .env
    networks:
      - default
    ports:
    - "3000:3000"
  service:
   container_name: mg_service
   build:
     context: ./service
     dockerfile: Dockerfile
   env_file: 
    - .env
   networks:
     - default
   ports:
   - "3001:3001"